---
  title: "US_Accidents_Analysis"
author: "Team: Bhoomika Nanjaraja, Khush Shah, Apoorva Reddy Bagepalli, Devarsh Apurva Sheth"
output:
  html_document:
  code_folding: show
number_sections: false
toc: yes
toc_depth: 3
toc_float: yes
pdf_document:
  toc: yes
toc_depth: '3'
---
  
```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes some helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# You will need to install it (once) from GitHub.
# library(devtools)
# devtools::install_github("physicsland/ezids")
# Then load the package in your R session.
library(ezids)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyverse)
library(scales)
library(plotly)
library(gridExtra)
library(tidytext)
library(modelr)
library(caret)
library(ROSE)
library(glmnet)
library(randomForest)
library(ggrepel)
library(patchwork)
library(readr)
library(corrplot)
```

```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

```{r}
accidents <- read_csv("/Users/bhoomikan/Desktop/DataScience_Project/US_Accidents.csv")
```

```{r}
head(accidents,n=5)
str(accidents)
```


```{r}
dataframe_cleaned <- na.omit(accidents)
str(dataframe_cleaned)

dataframe_cleaned$City <- as.factor(dataframe_cleaned$City)
names(dataframe_cleaned)[names(dataframe_cleaned) == "New Amenity"] <- "New_Amenity"
dataframe_cleaned$Amenity<- as.factor(dataframe_cleaned$Amenity)
dataframe_cleaned$New_Amenity<- as.factor(dataframe_cleaned$New_Amenity)
#dataframe_cleaned$`Response time`<- as.factor(dataframe_cleaned$`Response time`)
dataframe_cleaned$CityAbr <- substr(dataframe_cleaned$City, start = 1, stop = 3)
```
```{r}
str(dataframe_cleaned)
summary(dataframe_cleaned)
```
```{r}
ggplot(dataframe_cleaned, aes(x = CityAbr,fill = Amenity)) + geom_bar(position = "dodge")
```

```{r}
ggplot(dataframe_cleaned, aes(x = CityAbr,fill = New_Amenity)) + geom_bar(position = "dodge")
```
```{r}
category_counts <- table(dataframe_cleaned$Amenity)
barplot(category_counts, 
        main = "Bar Plot of Categories", 
        xlab = "Categories", 
        ylab = "Frequency",
        col = "blue")
```

```{r}
category_counts <- table(dataframe_cleaned$New_Amenity)
barplot(category_counts, 
        main = "Bar Plot of Categories", 
        xlab = "Categories", 
        ylab = "Frequency",
        col = "blue")
```
```{r}
ggplot(dataframe_cleaned, aes(x = `Response time`,fill = Amenity)) + geom_bar(position = "dodge")
```

```{r}
ggplot(dataframe_cleaned, aes(x = `Response time`,fill = New_Amenity)) + geom_bar(position = "dodge")
```

#If we look at the response time above,we can infer that the proportion of not requiring amenities always have an upper hand /are always algreater  irrespective of the response times.

```{r}
dataframe_cleaned$Sevprop_mod <- dataframe_cleaned$SeverityProportion * 1000000
dataframe_cleaned$Weights_mod <- dataframe_cleaned$Weights * 10000
unique_values1 <- unique(dataframe_cleaned$Sevprop_mod)
print(unique_values1)
unique_values2 <- unique(dataframe_cleaned$Weights_mod)
print(unique_values2)
```
```{r}
ggplot(dataframe_cleaned, aes(x = Sevprop_mod)) + 
     geom_boxplot() +
  labs(title = "Boxplot", 
       x = "SeverityProp", 
        y = "Count")+scale_x_continuous(limits = c(1, 10))
```
```{r}
ggplot(dataframe_cleaned, aes(x = Weights_mod)) + 
     geom_boxplot() +
  labs(title = "Boxplot", 
       x = "Weight", 
        y = "Count")+scale_x_continuous(limits = c(1, 10))
```
```{r}
df_sub <- subset(dataframe_cleaned,dataframe_cleaned$Amenity==0)
ggplot(df_sub, aes(x = Sevprop_mod, y = Weights_mod)) +
    geom_point(color = "blue") +  # Add points
    ggtitle("Scatter Plot of MPG vs. Weight") +
    xlab("Sev(Prop)") +
    ylab("Weights")
```

```{r}
df_sub <- subset(dataframe_cleaned,dataframe_cleaned$New_Amenity==0)
ggplot(df_sub, aes(x = Sevprop_mod, y = Weights_mod)) +
    geom_point(color = "blue") +  # Add points
    ggtitle("Scatter Plot of MPG vs. Weight") +
    xlab("Sev(Prop)") +
    ylab("Weights")
```


```{r}
df_subnew <- subset(dataframe_cleaned,dataframe_cleaned$Amenity==1)
ggplot(df_subnew, aes(x = Sevprop_mod, y = Weights_mod)) +
    geom_point(color = "blue") +  # Add points
    ggtitle("Scatter Plot of MPG vs. Weight") +
    xlab("Sev(Prop)") +
    ylab("Weights")
```
```{r}
df_subnew <- subset(dataframe_cleaned,dataframe_cleaned$New_Amenity==1)
ggplot(df_subnew, aes(x = Sevprop_mod, y = Weights_mod)) +
    geom_point(color = "blue") +  # Add points
    ggtitle("Scatter Plot of MPG vs. Weight") +
    xlab("Sev(Prop)") +
    ylab("Weights")
```
```{r}
ggplot(dataframe_cleaned, aes(x = Sevprop_mod, y = Weights_mod,color = New_Amenity)) +
    geom_point() +  
    ggtitle("Scatter Plot with Hue") +
    xlab("Sev(Prop)") +
    ylab("Weights") 
```
```{r}
ggplot(dataframe_cleaned, aes(x = Sevprop_mod, y = Weights_mod,color = Amenity)) +
    geom_point() +  
    ggtitle("Scatter Plot with Hue") +
    xlab("Sev(Prop)") +
    ylab("Weights") 
```

```{r}
numeric_data <- dataframe_cleaned[, sapply(dataframe_cleaned, is.numeric)]
cor_matrix <- cor(numeric_data)
corrplot(cor_matrix, method = "number")
```

```{r}
model <- glm(Amenity ~ Sevprop_mod + `Response time` , data = dataframe_cleaned, family = binomial)
summary(model)
predicted_probabilities <- predict(model, type = "response")
predicted_outcomes <- ifelse(predicted_probabilities > 0.5, 1, 0)
actual_outcomes <- dataframe_cleaned$Amenity
accuracy <- mean(predicted_outcomes == actual_outcomes)
print(accuracy)
```
```{r}
model <- glm(New_Amenity ~ Weights_mod, data = dataframe_cleaned, family = binomial)
summary(model)
predicted_probabilities <- predict(model, type = "response")
predicted_outcomes <- ifelse(predicted_probabilities > 0.001, 1, 0)
actual_outcomes <- dataframe_cleaned$Amenity
accuracy <- mean(predicted_outcomes == actual_outcomes)
print(accuracy)
```



